### PR TITLE
EZ

### PR DESCRIPTION
**Pull request by GinoPinus**
daje[https://www.google.com/imgres?q=tumblurr%20gif&imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1627328287985790976%2FZ8wURwLM_400x400.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fsdrogoblur&docid=SS-UteU80G3pyM&tbnid=C4aJze1t23-1WM&vet=12ahUKEwjLhMaFqtqFAxXD8QIHHTU9DrMQM3oECBMQAA..i&w=400&h=400&hcb=2&ved=2ahUKEwjLhMaFqtqFAxXD8QIHHTU9DrMQM3oECBMQAA](url)

### CODE REVIEW

**Comment by minehhh1** [comment]
no bro mi dispiace, ma rifiuto il tuo pull request

**Comment by GinoPinus** [comment]
image

**Comment by minehhh1** [comment]
nei ga

**Comment by minehhh1** [comment]
ingag

**Pull request merged**
